// ─── Shared type bindings ──────────────────────────────────────────────────────
// RiskLevel is generated by ts-rs from bridge-rs/src/types.rs.
// Regenerate with: cd core/native && cargo test -p bridge-rs
export type { RiskLevel } from "./bindings/RiskLevel"

export interface WsEvent<T = unknown> {
  type: string
  data: T
}

// ─── Device types ──────────────────────────────────────────────────────────────

export type DeviceKind = "desktop" | "mobile" | "server" | "other"
export type DevicePlatform = "windows" | "macos" | "linux" | "ios" | "android" | "other"
export type DeviceStatus = "online" | "offline" | "stale"

export interface NativeDevice {
  id: string
  display_name: string
  device_kind: DeviceKind
  platform: DevicePlatform
  client_version?: string
  capabilities: string[]
  is_enabled: boolean
  status: DeviceStatus
  last_seen_at?: string
  created_at: string
}

export interface IntegrationConnection {
  id: string
  provider: string
  account_ref?: string
  scopes: string[]
  health_status: string
  created_at: string
}

export interface AutomationRule {
  id: string
  name: string
  trigger: Record<string, unknown>
  condition?: Record<string, unknown>
  action: Record<string, unknown>
  approval_policy: string
  limit?: Record<string, unknown>
  is_active: boolean
  created_at: string
}

// ─── Run Center types (Run-centric model, §3.2) ────────────────────────────

// queued | running | waiting_approval | completed | failed | canceled
export type RunStatus = "queued" | "running" | "waiting_approval" | "completed" | "failed" | "canceled"

// pending | running | waiting_approval | succeeded | failed | rejected
export type ExecutionStatus = "pending" | "running" | "waiting_approval" | "succeeded" | "failed" | "rejected"

export type ApprovalDecision = "pending" | "approved" | "rejected"

export interface RunApproval {
  id: string
  execution_id: string
  run_id: string
  status: ApprovalDecision
  reason?: string
  requested_at: string
  decided_at?: string
  decided_by?: string
}

export interface RunExecution {
  id: string
  run_id: string
  kind: string
  status: ExecutionStatus
  risk_level: RiskLevel
  payload: Record<string, unknown>
  result?: Record<string, unknown>
  error_log?: string
  target_device_id?: string
  claimed_by_device_id?: string
  started_at?: string
  finished_at?: string
  created_at: string
  updated_at?: string
  approvals: RunApproval[]
}

export interface AgentRun {
  id: string
  user_id: string
  project_id?: string
  agent_id?: string
  session_id?: string
  status: RunStatus
  summary?: string
  started_at?: string
  finished_at?: string
  created_at: string
  updated_at?: string
  executions: RunExecution[]
}

export const WsRunEventType = {
  RUN_CREATED    : "run.created",
  RUN_UPDATED    : "run.updated",
  RUN_COMPLETED  : "run.completed",
  EXEC_CREATED   : "run.execution.created",
  EXEC_UPDATED   : "run.execution.updated",
  APPROVAL_REQ   : "run.approval.requested",
  APPROVAL_DONE  : "run.approval.decided",
} as const

export type WsRunEventType = typeof WsRunEventType[keyof typeof WsRunEventType]
