// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AutomationRule = {
  id: string;
  name: string;
  trigger: unknown;
  condition: unknown | null;
  action: unknown;
  approval_policy: string;
  limit: unknown | null;
  is_active: boolean;
  created_at: string;
};
