// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IntegrationConnection = {
  id: string;
  provider: string;
  account_ref: string | null;
  scopes: Array<string>;
  health_status: string;
  created_at: string;
};
