// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobStatus } from "./JobStatus";
import type { RiskLevel } from "./RiskLevel";

export type Job = {
  id: string;
  user_id: string;
  project_id: string | null;
  source: string;
  type: string;
  tags: Array<string>;
  status: JobStatus;
  risk_level: RiskLevel;
  payload: unknown;
  result: unknown | null;
  approved_by: string | null;
  error_log: string | null;
  created_at: string;
  started_at: string | null;
  finished_at: string | null;
  updated_at: string | null;
};
